# Generated by Django 5.2.6 on 2025-09-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
