# Generated by Django 5.2.6 on 2025-09-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='在庫数'),
        ),
    ]
