# Generated by Django 5.2.6 on 2025-09-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EC', '0006_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
    ]
